site_name: Genesis & Morningstar documentatie

use_directory_urls: false

theme:
  name: material
  favicon: Genesis/images/favicon.png
  logo: Genesis/images/combined_logo.png
  features:
    - content.code.copy
    - content.code.select

extra:
  generator: false

extra_css:
- stylesheets/extra.css

plugins:
  - offline
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: true
            show_root_heading: true
            show_symbol_type_toc: true
            summary: true
            filters:
              - "!^__"
              - "!^_"
              - "^__init__"
  - panzoom:
      full_screen: true

markdown_extensions:
  - attr_list
  - pymdownx.extra:
        pymdownx.superfences:
          custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Genesis:
      - Home: Genesis/index.md
      - Componenten:
          - Workflow:
              - Orkestrator: Genesis/Orchestrator/Orchestrator.md
              - Configuratie: Genesis/Orchestrator/Configuration.md
          - Power Designer extractie: Genesis/Extractor.md
          - Integreren ETL DAG: Genesis/Integrator/Integrator.md
          - Genereren DBs & ETL: Genesis/Generator.md
          - MDDE deployment code  : Genesis/Deploy_MDDE/Deploy_MDDE.md
          - DevOps repository management: Genesis/Repository_Manager.md
          - Hulp packages:
              - Logging: Genesis/Logtools.md
              - Documentatie genereren: Genesis/Documentation_Creation.md
  - Morningstar:
      - Home: Morningstar/index.md
  - Developers: Developers.md
