CREATE VIEW [DA_MDDE].[D_Date] AS 
SELECT [DateKey]
      ,[Date]
      ,[DayMonthNo]
      ,[DayQuarterNo]
      ,[DayYearNo]
      ,[StartWeekDate]
      ,[StartMonthDate]
      ,[StartQuarterDate]
      ,[StartYearDate]
      ,[EndWeekDate]
      ,[EndMontDate]
      ,[EndQuarterDate]
      ,[EndYearDate]
      ,[IsLeapYear]
      ,[IsWeekend]
      ,[YearNo]
      ,[YearNoIso]
      ,[YearNoDou]
      ,[QuarterNo]
      ,[MonthNo]
      ,[YearQuarterDesc]
      ,[YearMonthDesc]
      ,[YearWeekDesc]
      ,[YearWeekDescIso]
      ,[YearWeekDescDou]
      ,[MonthNameEN]
      ,[MonthNameNL]
      ,[MonthNameShortEN]
      ,[MonthNameShortNL]
      ,[WeekNo]
      ,[WeekNoIso]
      ,[WeekNoDou]
      ,[WeekDayNoEN]
      ,[WeekDayNoNL]
      ,[WeekDayNameEN]
      ,[WeekDayNameNL]
      ,[WeekDayOfMonth]
      ,[WeekDayNameShortEN]
      ,[WeekDayNameShortNL]
      ,[DateYesterday]
      ,[DateLastWeek]
      ,[DateLastMonth]
      ,[DateLastYear]
      ,[IsHoliday]
      ,[IsPublicHoliday]
  FROM [DM_Dim].[Date]
  WHERE [X_IsCurrent] = 1